include $(srctree)/drivers/misc/mediatek/video/mt8127/ccflags.mk

ifeq ($(CONFIG_MTK_OVERLAY_ENGINE_SUPPORT), y)
obj-y += \
    disp_ovl_engine_api.o \
    disp_ovl_engine_core.o \
    disp_ovl_engine_dev.o \
    disp_ovl_engine_sw.o \
    disp_ovl_engine_hw.o
endif
