include $(srctree)/drivers/misc/mediatek/video/mt8127/ccflags.mk

obj-$(CONFIG_MTK_FB) += disp_drv.o                  \
		mtkfb_console.o                            	\
		disp_assert_layer.o                       	\
		mtkfb.o                                   	\
		mtkfb_vsync.o								\
		mtkfb_pattern.o                            	\
		disp_debug.o                                    	\
		mtkfb_proc.o								\
		disp_drv_dbi.o								\
		disp_drv_dpi.o								\
		disp_drv_dsi.o								\
		disp_hal.o									\
		fbconfig_kdebug.o									\
		disp_intr.o

obj-$(CONFIG_MTK_OVERLAY_ENGINE_SUPPORT) += ovl_engine/


